### ISSUE TITLE
Redirect temp 2016 Leaderboard links to new 2016 Leaderboard 

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#34]
Redirect http://checkin2015-greenstreets.rhcloud.com/leaderboard/2016/ to http://checkinapp-greenstreets.rhcloud.com/leaderboard/2016/

**Comment by jkatzchristy** [comment]
Also, integrate data from http://checkin2015-greenstreets.rhcloud.com/leaderboard/2016/ to http://checkinapp-greenstreets.rhcloud.com/leaderboard/2016/ #38

**Comment by stephoj** [comment]
Data has been integrated. Correct April 2015 data on http://checkinapp-greenstreets.rhcloud.com/leaderboard/2015 and then delete http://checkin2015-greenstreets.rhcloud.com/leaderboard/2016/

**Comment by thecristen** [comment]
It turns out that data is missing from the leaderboard because there's no April 2015 month in the app... :(

![image](https://cloud.githubusercontent.com/assets/2136286/15373136/123051f0-1d12-11e6-8ab3-2dcca777d423.png)

Looks like it was overwritten with May 2016 checkin info. I will try to change it back tonight and hopefully everything else will fall into place...

**Comment by thecristen** [comment]
Done successfully!  http://checkinapp-greenstreets.rhcloud.com/leaderboard/2015/all/all/april/
