### ISSUE TITLE
Have cookies remember subteams + make subteams conditionally validating

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#39]
@thecristen @pwnage101 @Dustin21 The check-in is not collecting subteams for Cambridge, and I don't know if it's also happening for other orgs w/subteams, but it certainly may be. (I don't want to skew results by checking in as a test.)

Sub-teams are supposed to be req'd for orgs that have them. Do you know what the problem is, and why the problem? Can you figure out how soon this can be addressed?
THANKS!

**Comment by hl-public** [comment]
Hi Janie, Haihan here.
If you could let me know which branch you are working on I'll take a look at it and try to resolve the issue.

**Comment by jkatzchristy** [comment]
Thanks so much, @hhl60492. @thecristen said you should reach out to her with any questions.

**Comment by jkatzchristy** [comment]
This feature DID work in the 2015 check-in.

**Comment by thecristen** [comment]
Sorry for my delay, was wrapped up in work meetings. @hhl60492 I recommend creating a new branch off the latest master and then submitting a PR when you're done.

**Comment by thecristen** [comment]
Some notes which might be useful or relevant-
- all our validation is server-side right now.
- making subteams required in the model doesnt make much sense, since for most checkins there is no subteam. subteam is only required when checking in with an employer that has associated subteams
- there's probably some python/django way of making subteam conditionally required, but it might be easier to use javascript to prevent to user from checking in if there's a visible subteam `<select>` with no value filled in.

**Comment by hl-public** [comment]
Thanks, Cristen. I will work on making the subteam field conditional. Most likely have to add more columns and fields to the db.

Also I will try to merge with the changes in the QOTM branch and do a pull request soon.

**Comment by jkatzchristy** [comment]
@hhl60492 @thecristen  Any update on this?

**Comment by stephoj** [comment]
@thecristen to update and continue to work on once she has run @hhl60492 code
